<?php

namespace App\Http\Controllers;

use App\Models\alternatif;
use App\Models\kriteria;
use App\Models\penilaian;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class HasilAkhirController extends Controller
{
    public function index()
    {
        $data['kriteria'] = kriteria::all();
        $data['data'] = alternatif::all();
        $data['isi'] = penilaian::select('tb_penilaian.*','tb_subkriteria.bobot')->join('tb_subkriteria', 'tb_subkriteria.id', '=', 'tb_penilaian.id_subkriteria')->get();

        // ngambil data normalisasi
        $data['normalisasi'] = DB::select('SELECT get_bobot.*,tb_subkriteria.bobot FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,get_maxmin.jenis,get_maxmin.max_data,get_maxmin.min_data FROM `tb_penilaian` JOIN (SELECT tb_kriteria.id,tb_kriteria.kode_kriteria,tb_kriteria.nama_kriteria,tb_kriteria.jenis,maxmin.* FROM `tb_kriteria` JOIN (SELECT id_kriteria,MAX(bobot) AS max_data, MIN(bobot) AS min_data FROM `tb_subkriteria` GROUP BY id_kriteria) AS maxmin ON maxmin.id_kriteria = tb_kriteria.id) as get_maxmin ON get_maxmin.id = tb_penilaian.id_kriteria) as get_bobot join tb_subkriteria on tb_subkriteria.id = get_bobot.id_subkriteria');

        // ngambil data ahp
        $data['hasil'] = DB::select('SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b');

        // hasil akhir
        $data['hasilAkhir'] = DB::select('SELECT tb_alternatif.*,get_alternatif.hasil FROM(SELECT id_alternatif, SUM(matrik) AS hasil FROM (SELECT *, (normalisasi * bobot_ahp) AS matrik FROM(SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria)get_matrik) get_sum GROUP BY id_alternatif) get_alternatif JOIN tb_alternatif ON tb_alternatif.id = get_alternatif.id_alternatif WHERE tb_alternatif.deleted_at IS NULL ORDER BY hasil DESC');

        return view('hasilAkhir.index', $data);
    }
}


// get up to normalisasi
// SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi;


// normalisasi + ahp
// SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria;


// matriks before sum
// SELECT *, (normalisasi * bobot_ahp) AS matrik FROM(SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria)get_matrik;

// hasil without join data
// SELECT id_alternatif, SUM(matrik) AS hasil FROM (SELECT *, (normalisasi * bobot_ahp) AS matrik FROM(SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria)get_matrik) get_sum GROUP BY id_alternatif;

// done
// SELECT tb_alternatif.*,get_alternatif.hasil FROM(SELECT id_alternatif, SUM(matrik) AS hasil FROM (SELECT *, (normalisasi * bobot_ahp) AS matrik FROM(SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria)get_matrik) get_sum GROUP BY id_alternatif) get_alternatif JOIN tb_alternatif ON tb_alternatif.id = get_alternatif.id_alternatif;


// add deleted_at
// SELECT tb_alternatif.*,get_alternatif.hasil FROM(SELECT id_alternatif, SUM(matrik) AS hasil FROM (SELECT *, (normalisasi * bobot_ahp) AS matrik FROM(SELECT get_bobot.*,bobot.bobot_total AS bobot_ahp FROM (SELECT get_normalisasi.*,(get_normalisasi.bobot / get_normalisasi.bobot_max) AS normalisasi FROM(SELECT get_bobot.*,tb_subkriteria.bobot FROM(SELECT pure_data.*,get_maxmin.bobot_min,get_maxmin.bobot_max FROM (SELECT id,id_alternatif,id_kriteria,id_subkriteria FROM `tb_penilaian`) pure_data JOIN (SELECT id_alternatif,MIN(bobot) AS bobot_min, MAX(bobot) AS bobot_max FROM(SELECT * FROM (SELECT tb_penilaian.id,tb_penilaian.id_alternatif,tb_penilaian.id_kriteria,tb_penilaian.id_subkriteria,tb_subkriteria.bobot FROM `tb_penilaian` JOIN tb_subkriteria ON tb_subkriteria.id = id_subkriteria)a GROUP BY a.id) get_maxmin GROUP BY id_alternatif) AS get_maxmin ON get_maxmin.id_alternatif = pure_data.id_alternatif) get_bobot JOIN tb_subkriteria ON tb_subkriteria.id = get_bobot.id_subkriteria) get_normalisasi) get_bobot JOIN (SELECT tb_kriteria.*,toJoin.vector,toJoin.bobot as bobot_total FROM (SELECT hasil.*,(hasil.vector / hasil.total) as bobot FROM (SELECT get_vektor.id_kriteria_b,SUM(get_vektor.eigen) AS vector, COUNT(id_kriteria_a) as total FROM (SELECT *, (bobot/total) AS eigen FROM (SELECT tb_nilaiahp.*,a.total from (SELECT id_kriteria_a,SUM(bobot) as total FROM `tb_nilaiahp` GROUP BY id_kriteria_a) a JOIN tb_nilaiahp ON tb_nilaiahp.id_kriteria_a = a.id_kriteria_a) get_eigen) get_vektor GROUP BY get_vektor.id_kriteria_b) hasil) toJoin JOIN tb_kriteria ON tb_kriteria.id = toJoin.id_kriteria_b) as bobot ON bobot.id = get_bobot.id_kriteria)get_matrik) get_sum GROUP BY id_alternatif) get_alternatif JOIN tb_alternatif ON tb_alternatif.id = get_alternatif.id_alternatif WHERE tb_alternatif.deleted_at IS NULL;